### ISSUE TITLE
Remove legacy directory

### ISSUE THREAD

**Issue by matthewcarbone** [matthewcarbone/GGCE#65]
@Chiffafox feel free to remove this when you feel we've compiled everything into the main codebase. We can always add a tag called `legacy` and just leave that and point to the last commit where this code. I'm happy to do it but I don't want to step on your toes if you're still using it for something.

**Comment by x94carbone** [comment]
@Chiffafox bump! Can we finally remove this thing? 😁

**Comment by matthewcarbone** [comment]
@Chiffafox at this stage I think we need to purge it since it's affecting the code quality score 😁

Would it be ok for you to either create a local copy or just keep it on another branch?

**Comment by Chiffafox** [comment]
@matthewcarbone I think the main issue for the code quality score was the use of `pickle` though, based on what I saw when I reviewed that analysis.

**Comment by matthewcarbone** [comment]
Eh- it's possible. Might as well be thorough though.
